
	window.localStorage.setItem('linguage_001','As informações foram atualizadas!');
	window.localStorage.setItem('linguage_002','E-mail');
	window.localStorage.setItem('linguage_003','Senha');
	window.localStorage.setItem('linguage_004','Acessar');
	window.localStorage.setItem('linguage_005','Esqueci minha senha');
	window.localStorage.setItem('linguage_006','Criar uma nova conta');
	window.localStorage.setItem('linguage_007','O campo E-mail deve ser preenchido');
	window.localStorage.setItem('linguage_008','O campo Senha deve ser preenchido');
	window.localStorage.setItem('linguage_009','O E-mail ou a Senha utilizados não são válidos');
	window.localStorage.setItem('linguage_010','Nome Completo');
	window.localStorage.setItem('linguage_011','Empresa');
	window.localStorage.setItem('linguage_012','Telefone');
	window.localStorage.setItem('linguage_013','Quero me Cadastrar');
	window.localStorage.setItem('linguage_014','Voltar');
	window.localStorage.setItem('linguage_015','O campo Nome deve ser preenchido');
	window.localStorage.setItem('linguage_016','O campo Empresa deve ser preenchido');
	window.localStorage.setItem('linguage_017','O campo Telefone deve ser preenchido');
	window.localStorage.setItem('linguage_018','Esse E-mail já foi utilizado em outro Cadastro');
	window.localStorage.setItem('linguage_019','Não foi possuível concluir o seu cadastro, tente novamente mais tarde!');
	window.localStorage.setItem('linguage_020','<b>CADASTRE-SE</b>');
	window.localStorage.setItem('linguage_021','Preencha todos os campos abaixo para se cadastrar e ter acesso ao nosso catálogo de produtos.');
	window.localStorage.setItem('linguage_022','<b>SUCESSO!<b>');
	window.localStorage.setItem('linguage_023','Cadastro realizado com sucesso!<br><br>Você já pode continuar e<br>acessar o nosso catálogo.');
	window.localStorage.setItem('linguage_024','Acessar Catálogo');
	window.localStorage.setItem('linguage_025','<b>RECUPERAR<b>');
	window.localStorage.setItem('linguage_026','<h3 style="color:#000;">Esqueci minha senha</h3>Utilize o campo abaixo para informar o Email utilizado no cadastro e iremos enviar sua senha.');
	window.localStorage.setItem('linguage_027','Enviar senha por e-mail');
	window.localStorage.setItem('linguage_028','Não foi encontrado nenhum cadastro com esse E-mail!');
	window.localStorage.setItem('linguage_029','E-mail enviado com sucesso!<br>Em breve você recebera por e-mail, um link para cadastrar uma nova senha.');
	window.localStorage.setItem('linguage_030','<b>FILTRAR<b>');
	window.localStorage.setItem('linguage_031','Buscar');
	window.localStorage.setItem('linguage_032','Lançamentos');
	window.localStorage.setItem('linguage_033','Notícias');
	window.localStorage.setItem('linguage_034','Contato');
	window.localStorage.setItem('linguage_035','Filtrando por');
	window.localStorage.setItem('linguage_036','Montadora');
	window.localStorage.setItem('linguage_037','Automóveis');
	window.localStorage.setItem('linguage_038','Caminhões');
	window.localStorage.setItem('linguage_039','Ônibus');
	window.localStorage.setItem('linguage_040','Tratores');
	window.localStorage.setItem('linguage_041','Motocicletas');
	window.localStorage.setItem('linguage_042','Máquinas e Equipamentos');
	window.localStorage.setItem('linguage_043','Conversão Direta');
	window.localStorage.setItem('linguage_044','');
	window.localStorage.setItem('linguage_045','');
	window.localStorage.setItem('linguage_046','');
	window.localStorage.setItem('linguage_047','');
	window.localStorage.setItem('linguage_048','');
	window.localStorage.setItem('linguage_049','');
	window.localStorage.setItem('linguage_050','');
	window.localStorage.setItem('linguage_051','');
	window.localStorage.setItem('linguage_052','');
	window.localStorage.setItem('linguage_053','');
	window.localStorage.setItem('linguage_054','');
	window.localStorage.setItem('linguage_055','');
	window.localStorage.setItem('linguage_056','');
	window.localStorage.setItem('linguage_057','');
	window.localStorage.setItem('linguage_058','');
	window.localStorage.setItem('linguage_059','');
	window.localStorage.setItem('linguage_060','');
	